### ISSUE TITLE
npm install does not work

### ISSUE THREAD

**Issue by layssi** [Panopticon-AI-team/panopticon#110]
**Describe the bug**
0 verbose cli /home/usr/.nvm/versions/node/v18.20.5/bin/node /home/usr/.nvm/versions/node/v18.20.5/bin/npm
1 info using npm@10.8.2
2 info using node@v18.20.5
3 silly config load:file:/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/npmrc
4 silly config load:file:/home/usr/panopticon/client/.npmrc
5 silly config load:file:/home/usr/.npmrc
6 silly config load:file:/home/usr/.nvm/versions/node/v18.20.5/etc/npmrc
7 verbose title npm install
8 verbose argv "install"
9 verbose logfile logs-max:10 dir:/home/usr/.npm/_logs/2024-12-04T13_48_27_363Z-
10 verbose logfile /home/usr/.npm/_logs/2024-12-04T13_48_27_363Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest react@^16.8.0 || ^17.0.0
16 silly packumentCache full:https://registry.npmjs.org/react cache-miss
17 http fetch GET 200 https://registry.npmjs.org/react 479ms (cache revalidated)
18 silly packumentCache full:https://registry.npmjs.org/react set size:5195970 disposed:false
19 silly fetch manifest react-dom@^16.8.0 || ^17.0.0
20 silly packumentCache full:https://registry.npmjs.org/react-dom cache-miss
21 http fetch GET 200 https://registry.npmjs.org/react-dom 84ms (cache revalidated)
22 silly packumentCache full:https://registry.npmjs.org/react-dom set size:6383148 disposed:false
23 silly fetch manifest @types/react@^16.8.6 || ^17.0.0
24 silly packumentCache full:https://registry.npmjs.org/@types%2freact cache-miss
25 http fetch GET 200 https://registry.npmjs.org/@types%2freact 46ms (cache revalidated)
26 silly packumentCache full:https://registry.npmjs.org/@types%2freact set size:2224167 disposed:false
27 verbose stack Error: could not resolve
27 verbose stack     at PlaceDep.failPeerConflict (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:503:25)
27 verbose stack     at new PlaceDep (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:157:21)
27 verbose stack     at #buildDepStep (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:18)
27 verbose stack     at async Arborist.buildIdealTree (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
27 verbose stack     at async Promise.all (index 1)
27 verbose stack     at async Arborist.reify (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
27 verbose stack     at async Install.exec (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/lib/commands/install.js:150:5)
27 verbose stack     at async Npm.exec (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/lib/npm.js:207:9)
27 verbose stack     at async module.exports (/home/usr/.nvm/versions/node/v18.20.5/lib/node_modules/npm/lib/cli/entry.js:74:5)
28 error code ERESOLVE
29 error ERESOLVE could not resolve
30 error
31 error While resolving: @material-ui/core@4.12.4
31 error Found: @types/react@18.2.47
31 error node_modules/@types/react
31 error   dev @types/react@"^18.2.47" from the root project
31 error   peerOptional @types/react@"*" from @material-ui/types@5.1.0
31 error   node_modules/@material-ui/types
31 error     @material-ui/types@"5.1.0" from @material-ui/core@4.12.4
31 error     node_modules/@material-ui/core
31 error       @material-ui/core@"^4.12.4" from the root project
31 error     @material-ui/types@"5.1.0" from @material-ui/styles@4.11.5
31 error     node_modules/@material-ui/styles
31 error       @material-ui/styles@"^4.11.5" from the root project
31 error       1 more (@material-ui/core)
31 error   9 more (@mui/base, @mui/icons-material, @mui/material, ...)
31 error
31 error Could not resolve dependency:
31 error peerOptional @types/react@"^16.8.6 || ^17.0.0" from @material-ui/core@4.12.4
31 error node_modules/@material-ui/core
31 error   @material-ui/core@"^4.12.4" from the root project
31 error
31 error Conflicting peer dependency: @types/react@17.0.83
31 error node_modules/@types/react
31 error   peerOptional @types/react@"^16.8.6 || ^17.0.0" from @material-ui/core@4.12.4
31 error   node_modules/@material-ui/core
31 error     @material-ui/core@"^4.12.4" from the root project
31 error
31 error Fix the upstream dependency conflict, or retry
31 error this command with --force or --legacy-peer-deps
31 error to accept an incorrect (and potentially broken) dependency resolution.
32 error
32 error
32 error For a full report see:
32 error /home/usr/.npm/_logs/2024-12-04T13_48_27_363Z-eresolve-report.txt
33 silly unfinished npm timer reify 1733320107574
34 silly unfinished npm timer reify:loadTrees 1733320107576
35 silly unfinished npm timer idealTree:buildDeps 1733320108041
36 silly unfinished npm timer idealTree:node_modules/@material-ui/core 1733320108042
37 verbose cwd /home/usr/panopticon/client
38 verbose os Linux 5.15.0-125-generic
39 verbose node v18.20.5
40 verbose npm  v10.8.2
41 verbose exit 1
42 verbose code 1

**To Reproduce**
1. Go to '...' client/src

**Expected behavior**
I tried everything and this is not installing.
ubuntu 20
I

**Screenshots**

**Additional context**

**Comment by orgulous** [comment]
thank you for this message, we will look into it.

**Comment by duyminh1998** [comment]
@layssi try `npm install --legacy-peer-deps`

**Comment by layssi** [comment]
It worked. Oddly I did try that yesterday and that did not work.  We

**Comment by layssi** [comment]
It worked. Oddly I did try that yesterday and that did not work.  We can close it for now.
