### ISSUE TITLE
Usability Cleanup

### ISSUE THREAD

**Issue by duyminh1998** [Panopticon-AI-team/panopticon#88]
- [x] Reference points should have their own button because they are conceptually distinct from adding units 
- [x] Change Teleport Wording to “Edit Location”
- [x] #90
- [x] Toggle should be on “inspect” by default, then red or blue. So the toggle should have 3 states.
- [x] Change wording to “Edit Unit Missions” & have separate section for it
- [x] Add fuel to aircraft so that they don’t disappear so quickly

**Comment by orgulous** [comment]
looks like everything under usability cleanup is in here.

**Comment by duyminh1998** [comment]
@orgulous can you review the [usability branch](https://github.com/Panopticon-AI-team/panopticon/tree/88-usability-cleanup) and test out the God Mode functionality? Currently on God Mode you can do a lot of things to both sides but there might be some weird/unwanted interactions (e.g. if you are on Blue side and on God mode, plotting a course for a red aircraft will result in the measurement line being colored blue instead of red). Please identify any additional quirks and advise if we should proceed with God Mode as implemented or improve further.

**Comment by orgulous** [comment]
This looks fine, I think we can push to main after the bug is fixed
